server:
  port: 9000

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer